version: '3'
services:
  sports_push_up:
    container_name: sports_push_up
    image: windymuse/sports_push_up:1.0.0
    environment:
      TZ: Asia/Shanghai
    hostname: sports_push_up
    restart: always
    ports:
      - "5001:5001"
