version: '3'
services:
  sports_sit_up:
    container_name: sports_sit_up
    image: windymuse/sports_sit_up:1.0.0
    environment:
      TZ: Asia/Shanghai
    hostname: sports_sit_up
    restart: always
    ports:
      - "5001:5001"
